use p256::ecdsa::SigningKey;
use p256::pkcs8::{DecodePrivateKey, EncodePrivateKey};
use sha2::{Digest, Sha256};
use std::path::Path;

pub fn generate(out_path: &Path, out_rust: Option<&Path>) -> anyhow::Result<()> {
    let signing_key = SigningKey::random(&mut rand_core::OsRng);
    let pem = signing_key.to_pkcs8_pem(Default::default())?;
    std::fs::write(out_path, pem.as_bytes())?;

    let fingerprint = pubkey_fingerprint(signing_key.verifying_key());
    println!("Key written to {}", out_path.display());
    println!("Public key fingerprint (SHA-256): {}", fingerprint);

    if let Some(rust_path) = out_rust {
        let point = signing_key.verifying_key().to_encoded_point(false);
        let coords = point.as_bytes();
        // uncompressed: 0x04 || x(32) || y(32)
        let x = &coords[1..33];
        let y = &coords[33..65];
        let x_str = fmt_byte_array(x);
        let y_str = fmt_byte_array(y);
        let content = format!(
            "// Generated by: sign-image keygen --out {} --out-rust {}\n\
             // Fingerprint (SHA-256 of uncompressed point): {}\n\
             pub const PUB_KEY_X: [u8; 32] = {};\n\
             pub const PUB_KEY_Y: [u8; 32] = {};\n",
            out_path.display(),
            rust_path.display(),
            fingerprint,
            x_str,
            y_str,
        );
        std::fs::write(rust_path, content)?;
        println!("Rust key constants written to {}", rust_path.display());
    }
    Ok(())
}

fn fmt_byte_array(bytes: &[u8]) -> String {
    let inner: Vec<String> = bytes.iter().map(|b| format!("0x{:02x}", b)).collect();
    format!("[{}]", inner.join(", "))
}

pub fn load_signing_key(pem_path: &Path) -> anyhow::Result<SigningKey> {
    let pem = std::fs::read_to_string(pem_path)?;
    let key = SigningKey::from_pkcs8_pem(&pem)?;
    Ok(key)
}

pub fn pubkey_fingerprint(vk: &p256::ecdsa::VerifyingKey) -> String {
    let point = vk.to_encoded_point(false);
    let mut hasher = Sha256::new();
    hasher.update(point.as_bytes());
    hex::encode(hasher.finalize())
}
